### ISSUE TITLE
Scripthook v1.0.1180.2 game crash

### ISSUE THREAD

**Issue by frmsvrt** [ai-tor/DeepGTAV#71] opened 2017-09-05 07:34 UTC
It seems game crash every time when i trying connect to the server with new scripthook v1.0.1180.2 update, with error by:
scripthook V -- critical error: fatal can't find native 0x80E4A6EDDB0BE8D9 
I've tried use older one build, but there is no changes. Any suggestions?

**Comment by dominikandreas** [comment] 2017-09-05 07:39
Other users at http://gtaforums.com/topic/788343-script-hook-v/page-218 have posted the same issue. Seems LOAD_ALL_PATH_NODES has been removed in the latest update. One user suggests using this function instead which is supposedly the same: http://www.dev-c.com/nativedb/func/info/f7b79a50b905a30d

**Comment by frmsvrt** [comment] 2017-09-05 13:32
Ok, seems there will be a lot of changes in future. Close this issue.

**Comment by dominikandreas** [comment] 2017-09-05 13:35
Why close it if the issue isn't fixed? I'd keep it open until someone fixed it in the code. That way other users can know which parts of the code can fail and don't open redundant issues

**Comment by frmsvrt** [comment] 2017-09-06 06:37
Your truth! Reopen it. Commented LOAD_ALL_PATH_NODES  in code, but still get an error, for now it goes from `dct = json.loads(jsonstr)` while receive messages from server.

**Comment by ai-tor** [comment] 2017-09-06 10:39
It seems that this new update breaks the whole Reward functionality. Try to remove the reward field from the list of fields in the VPilot dataset message. Hopefully that will workaround the issue until I fix it.

**Comment by IanKirwan** [comment] 2017-09-06 11:07
@frmsvrt could you post up the mods you did to remove LOAD_ALL_PATH_NODES?
I'll try the mod to Vpilot suggested by ai-tor.

**Comment by IanKirwan** [comment] 2017-09-06 17:18
Hi @ai-tor 
I'm not all that familiar with Github. Just wondering if there is a way to do 'releases' so that folks with working GTAV 1.1103.1 versions can access that code, and the mods to make it work with 1.1180.1 can carry on in the 'trunk' code.

**Comment by ai-tor** [comment] 2017-09-07 08:23
@IanKirwan Yes, to keep releases is something I definitely want to do. 

I also let you know that the compatibility with the last GTAV version has now been fixed and so I close the issue. :)

**Closed by ai-tor** 2017-09-07 08:23 UTC
